import { HttpException } from "@/exceptions/HttpException";
import { ResponseCodes, ResponseMessages } from "@/interfaces/response.interface";
import { ETaxType, ITax } from "@/interfaces/tax.interface";
import { IUser } from "@/interfaces/users.interface";
import taxModel from "@/models/tax.model";
import { getNameAndSurname, numberToStr, removeEmptyKeys } from "@/utils/util";

class TaxService {
    public async getTaxesList(year: number, trimester: number, userId: string): Promise<ITax[]> {
        const taxes = await taxModel.find({ year, trimester, userId })
        return taxes
    }

    public async addUpdateTax(taxData: ITax): Promise<ITax> {
        const filteredData: ITax = removeEmptyKeys(taxData)
        const tax = await taxModel.findOneAndUpdate({ year: filteredData.year, trimester: filteredData.trimester, userId: filteredData.userId, type: filteredData.type }, filteredData, { upsert: true, new: true })
        return tax
    }

    public async resetTax(year: number, trimester: number, type: ETaxType, userId: string): Promise<ITax> {
        const tax = await taxModel.findOneAndUpdate({ year: year, trimester: trimester, userId: userId, type: type }, { $unset: { data: 1 } }, { upsert: true, new: true })
        return tax
    }

    public async generateTxt(type: ETaxType, year: number, trimester: number, user: IUser): Promise<string> {
        const tax = await taxModel.findOne({ type, year, trimester, userId: user._id })
        if (!tax)
            throw new HttpException(ResponseCodes.NOT_FOUND, ResponseMessages.en.TAX_NOT_FOUND)
        if (tax.type === ETaxType.FORM130)
            return this.getForm130TxtData(year, trimester, user.cifNif, user.name, tax)
        if (tax.type === ETaxType.FORM303 && year < 2022)
            return this.getForm303Content(year, trimester, user.cifNif, user.name, tax)
        if (tax.type === ETaxType.FORM303)
            return this.getForm303Content2022(year, trimester, user.cifNif, user.name, tax)
        if (tax.type === ETaxType.FORM111)
            return this.getForm111TxtData(year, trimester, user.cifNif, user.name, tax)
        if (tax.type === ETaxType.FORM115)
            return this.getForm115TxtData(year, trimester, user.cifNif, user.name, tax)
    }

    private getForm115TxtData(year: number, trimester: number, cifNif: string, name: string, tax: ITax): string {
        const data = tax.data
        const nameSurname = getNameAndSurname(name)
        // if (Object.values(data).length < 30) throw new HttpException(ResponseCodes.BAD_REQUEST, ResponseMessages.en.FORM_INVALID_DATA)
        return "<T1150" + year + trimester + "T0000><AUX>"
            + "1.9".padStart(70 + 4, ' ') // 70 blank + 4 version string
            + "B88476437".padStart(9 + 4, ' ') // 9 NIF + 4 blanks
            + "</AUX>".padStart(213 + 6, ' ') // 213 blank space + </AUX>
            + "<T11501000> "//----- FIRST PAGE ------
            + (parseFloat(data['30']) && parseFloat(data['30']) <= 0 ? "N" : "I")
            + cifNif
            + nameSurname.surname.padEnd(60, ' ')
            + nameSurname.name.padEnd(20, ' ')
            + year
            + trimester + "T"
            + numberToStr(data["1"], 15, 1)
            + numberToStr(data["2"], 17)
            + numberToStr(data["3"], 17)
            + numberToStr(data["4"], 17)
            + numberToStr(data["5"], 17)
            + String(data['6'] || " ").charAt(0)
            + String(data['7'] || "").padStart(13, ' ')
            + "</T11501000>".padStart(34 + 236 + 13 + 12, ' ') // 389 + 13 spaces + 12 tag
            + "</T1150" + year + trimester + "T0000>"
    }

    private getForm111TxtData(year: number, trimester: number, cifNif: string, name: string, tax: ITax): string {
        const data = tax.data
        const nameSurname = getNameAndSurname(name)
        // if (Object.values(data).length < 30) throw new HttpException(ResponseCodes.BAD_REQUEST, ResponseMessages.en.FORM_INVALID_DATA)
        return "<T1110" + year + trimester + "T0000><AUX>"
            + "1.9".padStart(70 + 4, ' ') // 70 blank + 4 version string
            + "B88476437".padStart(9 + 4, ' ') // 9 NIF + 4 blanks
            + "</AUX>".padStart(213 + 6, ' ') // 213 blank space + </AUX>
            + "<T11101000> "//----- FIRST PAGE ------
            + (parseFloat(data['30']) && parseFloat(data['30']) <= 0 ? "N" : "I")
            + cifNif
            + nameSurname.surname.padEnd(60, ' ')
            + nameSurname.name.padEnd(20, ' ')
            + year
            + trimester + "T"
            + numberToStr(data["1"], 8, 1)
            + numberToStr(data["2"], 17)
            + numberToStr(data["3"], 17)
            + numberToStr(data["4"], 8, 1)
            + numberToStr(data["5"], 17)
            + numberToStr(data["6"], 17)
            + numberToStr(data["7"], 8, 1)
            + numberToStr(data["8"], 17)
            + numberToStr(data["9"], 17)
            + numberToStr(data["10"], 8, 1)
            + numberToStr(data["11"], 17)
            + numberToStr(data["12"], 17)
            + numberToStr(data["13"], 8, 1)
            + numberToStr(data["14"], 17)
            + numberToStr(data["15"], 17)
            + numberToStr(data["16"], 8, 1)
            + numberToStr(data["17"], 17)
            + numberToStr(data["18"], 17)
            + numberToStr(data["19"], 8, 1)
            + numberToStr(data["20"], 17)
            + numberToStr(data["21"], 17)
            + numberToStr(data["22"], 8, 1)
            + numberToStr(data["23"], 17)
            + numberToStr(data["24"], 17)
            + numberToStr(data["25"], 8, 1)
            + numberToStr(data["26"], 17)
            + numberToStr(data["27"], 17)
            + numberToStr(data["28"], 17)
            + numberToStr(data["29"], 17)
            + numberToStr(data["30"], 17)
            + String(data['31'] || " ").charAt(0)
            + String(data['32'] || "").padStart(13, ' ')
            + String(data['33'] || " ").charAt(0)
            + String(data['34'] || "").padStart(34, ' ')
            + "</T11101000>".padStart(389 + 13 + 12, ' ') // 389 + 13 spaces + 12 tag
            + "</T1110" + year + trimester + "T0000>"
    }

    private getForm130TxtData(year: number, trimester: number, cifNif: string, name: string, tax: ITax): string {
        const data = tax.data
        // if (Object.values(data).length < 20) throw new HttpException(ResponseCodes.BAD_REQUEST, ResponseMessages.en.FORM_INVALID_DATA)
        const nameSurname = getNameAndSurname(name)
        return "<T1300" + year + trimester + "T0000><AUX>"
            + "1.06".padStart(70 + 4, ' ') // 70 blank + 4 version string
            + "B88476437".padStart(9 + 4, ' ') // 9 NIF + 4 blanks
            + "</AUX>".padStart(213 + 6, ' ') // 213 blank space + </AUX>
            + "<T13001000> "//----- FIRST PAGE ------
            + (parseFloat(data['18']) && parseFloat(data['18']) < 0 ? "B" : (parseFloat(data['18']) && parseFloat(data['18']) === 0 ? "N" : "I"))
            + cifNif
            + nameSurname.surname.padEnd(60, ' ')
            + nameSurname.name.padEnd(20, ' ')
            + year
            + trimester + "T"
            + numberToStr(data['0'], 17)
            + numberToStr(data['1'], 17)
            + numberToStr(data['2'], 17)
            + numberToStr(data['3'], 17)
            + numberToStr(data['4'], 17)
            + numberToStr(data['5'], 17)
            + numberToStr(data['6'], 17)
            + numberToStr(data['7'], 17)
            + numberToStr(data['8'], 17)
            + numberToStr(data['9'], 17)
            + numberToStr(data['10'], 17)
            + numberToStr(data['11'], 17)
            + numberToStr(data['12'], 17)
            + numberToStr(data['13'], 17)
            + numberToStr(data['14'], 17)
            + numberToStr(data['15'], 17)
            + numberToStr(data['16'], 17)
            + numberToStr(data['17'], 17)
            + numberToStr(data['18'], 17)
            + " "
            + String(data['19'] || '').padStart(13, ' ')
            + String(data['20'] || '').padStart(34, ' ')
            + "</T13001000>".padStart(96 + 13 + 12, ' ')    // 590 spaces + 12 tag
            + "</T1300" + year + trimester + "T0000>"
    }
    private getForm303Content(year: number, trimester: number, cifNif: string, name: string, tax: ITax): string {
        const data = tax.data
        // if (Object.values(data).length < 180) throw new HttpException(ResponseCodes.BAD_REQUEST, ResponseMessages.en.FORM_INVALID_DATA)
        return "<T3030" + year + trimester + "T0000><AUX>"
            + "2.05".padStart(70 + 4, ' ') // 70 blank + 4 version string
            + "B88476437".padStart(9 + 4, ' ') // 9 NIF + 4 blanks
            + "</AUX>".padStart(213 + 6, ' ') // 213 blank space + </AUX>
            + "<T30301000> A" //----- FIRST PAGE ------
            + cifNif
            + name.padEnd(80, ' ')
            + year
            + trimester
            + "T"
            + String(data['0'] || "2").charAt(0)
            + String(data['1'] || "2").charAt(0)
            + String(data['2'] || "3").charAt(0)
            + String(data['3'] || "2").charAt(0)
            + String(data['4'] || "2").charAt(0)
            + String(data['5'] || "2").charAt(0)
            + String(data['6'] || "2").charAt(0)
            + String(data['7'] || "2").charAt(0)
            + String(data['8'] || "2").charAt(0)
            + String(data['9'] || '').padStart(8, ' ')
            + String(data['10'] || " ").charAt(0)
            + String(data['11'] || "2").charAt(0)
            + String(data['12'] || "0").charAt(0)
            + String(data['13'] || "0").charAt(0)
            + numberToStr(data['14'], 17)
            + numberToStr(data['15'], 5)
            + numberToStr(data['16'], 17)
            + numberToStr(data['17'], 17)
            + numberToStr(data['18'], 5)
            + numberToStr(data['19'], 17)
            + numberToStr(data['20'], 17)
            + numberToStr(data['21'], 5)
            + numberToStr(data['22'], 17)
            + numberToStr(data['23'], 17)
            + numberToStr(data['24'], 17)
            + numberToStr(data['25'], 17)
            + numberToStr(data['26'], 17)
            + numberToStr(data['27'], 17)
            + numberToStr(data['28'], 17)
            + numberToStr(data['29'], 17)
            + numberToStr(data['30'], 5)
            + numberToStr(data['31'], 17)
            + numberToStr(data['32'], 17)
            + numberToStr(data['33'], 5)
            + numberToStr(data['34'], 17)
            + numberToStr(data['35'], 17)
            + numberToStr(data['36'], 5)
            + numberToStr(data['37'], 17)
            + numberToStr(data['38'], 17)
            + numberToStr(data['39'], 17)
            + numberToStr(data['40'], 17)
            + numberToStr(data['41'], 17)
            + numberToStr(data['42'], 17)
            + numberToStr(data['43'], 17)
            + numberToStr(data['44'], 17)
            + numberToStr(data['45'], 17)
            + numberToStr(data['46'], 17)
            + numberToStr(data['47'], 17)
            + numberToStr(data['48'], 17)
            + numberToStr(data['49'], 17)
            + numberToStr(data['50'], 17)
            + numberToStr(data['51'], 17)
            + numberToStr(data['52'], 17)
            + numberToStr(data['53'], 17)
            + numberToStr(data['54'], 17)
            + numberToStr(data['55'], 17)
            + numberToStr(data['56'], 17)
            + numberToStr(data['57'], 17)
            + numberToStr(data['58'], 17)
            + numberToStr(data['59'], 17)
            + "</T30301000>".padStart(600 + 13 + 12, ' ')    // 600 spaces + 13 spaces + 12 tag
            + "<T30302000>"//----- SECOND PAGE ------
            + String(data['60'] || " ").charAt(0)
            + String(data['61'] || '').padStart(2, '0')
            + numberToStr(data['62'], 17)
            + numberToStr(data['63'], 6, 100000)
            + numberToStr(data['64'], 17)
            + numberToStr(data['65'], 5)
            + numberToStr(data['66'], 17)
            + numberToStr(data['67'], 17)
            + numberToStr(data['68'], 17)
            + String(data['69'] || '').padStart(2, '0')
            + numberToStr(data['70'], 17)
            + numberToStr(data['71'], 6, 100000)
            + numberToStr(data['72'], 17)
            + numberToStr(data['73'], 5)
            + numberToStr(data['74'], 17)
            + numberToStr(data['75'], 17)
            + numberToStr(data['76'], 17)
            + String(data['77'] || '').padStart(4, ' ')
            + String(data['78'] || " ").charAt(0)
            + numberToStr(data['79'], 10)
            + numberToStr(data['80'], 17)
            + numberToStr(data['81'], 10)
            + numberToStr(data['82'], 17)
            + numberToStr(data['83'], 10)
            + numberToStr(data['84'], 17)
            + numberToStr(data['85'], 10)
            + numberToStr(data['86'], 17)
            + numberToStr(data['87'], 10)
            + numberToStr(data['88'], 17)
            + numberToStr(data['89'], 10)
            + numberToStr(data['90'], 17)
            + numberToStr(data['91'], 10)
            + numberToStr(data['92'], 17)
            + numberToStr(data['93'], 17)
            + numberToStr(data['94'], 17)
            + numberToStr(data['95'], 3)
            + numberToStr(data['96'], 5)
            + numberToStr(data['97'], 17)
            + numberToStr(data['98'], 17)
            + numberToStr(data['99'], 3)
            + numberToStr(data['100'], 17)
            + numberToStr(data['101'], 5)
            + numberToStr(data['102'], 17)
            + numberToStr(data['103'], 17)
            + numberToStr(data['104'], 17)
            + String(data['105'] || '').padStart(4, ' ')
            + String(data['106'] || " ").charAt(0)
            + numberToStr(data['107'], 10)
            + numberToStr(data['108'], 17)
            + numberToStr(data['109'], 10)
            + numberToStr(data['110'], 17)
            + numberToStr(data['111'], 10)
            + numberToStr(data['112'], 17)
            + numberToStr(data['113'], 10)
            + numberToStr(data['114'], 17)
            + numberToStr(data['115'], 10)
            + numberToStr(data['116'], 17)
            + numberToStr(data['117'], 10)
            + numberToStr(data['118'], 17)
            + numberToStr(data['119'], 10)
            + numberToStr(data['120'], 17)
            + numberToStr(data['121'], 17)
            + numberToStr(data['122'], 17)
            + numberToStr(data['123'], 3)
            + numberToStr(data['124'], 5)
            + numberToStr(data['125'], 17)
            + numberToStr(data['126'], 17)
            + numberToStr(data['127'], 3)
            + numberToStr(data['128'], 17)
            + numberToStr(data['129'], 5)
            + numberToStr(data['130'], 17)
            + numberToStr(data['131'], 17)
            + numberToStr(data['132'], 17)
            + numberToStr(data['133'], 17)
            + numberToStr(data['134'], 17)
            + numberToStr(data['135'], 17)
            + numberToStr(data['136'], 17)
            + numberToStr(data['137'], 17)
            + numberToStr(data['138'], 17)
            + numberToStr(data['139'], 17)
            + numberToStr(data['140'], 17)
            + numberToStr(data['141'], 17)
            + numberToStr(data['142'], 17)
            + numberToStr(data['143'], 17)
            + numberToStr(data['144'], 17)
            + "</T30302000>".padStart(590 + 12, ' ')    // 590 spaces + 12 tag


            + "<T30303000>"//----- THIRD PAGE ------
            + numberToStr(data['145'], 17)
            + numberToStr(data['146'], 17)
            + numberToStr(data['147'], 17)
            + numberToStr(data['148'], 17)
            + String(data['149'] || '').padStart(17, '0')
            + numberToStr(data['150'], 17)
            + numberToStr(data['151'], 17)
            + numberToStr(data['152'], 17)
            + numberToStr(data['153'], 17)
            + numberToStr(data['154'], 17)
            + numberToStr(data['155'], 17)
            + numberToStr(data['156'], 17)
            + numberToStr(data['157'], 17)
            + numberToStr(data['158'], 17)
            + numberToStr(data['159'], 5)
            + numberToStr(data['160'], 17)
            + numberToStr(data['161'], 17)
            + numberToStr(data['162'], 17)
            + numberToStr(data['163'], 17)
            + numberToStr(data['164'], 17)
            + numberToStr(data['165'], 17)
            + numberToStr(data['166'], 17)
            + numberToStr(data['167'], 17)
            + numberToStr(data['168'], 17)
            + String(data['169'] || " ").charAt(0)
            + String(data['170'] || '').padStart(13, ' ')
            + String(data['171'] || " ").charAt(0)
            + String(data['172'] || '').padStart(11, ' ')
            + String(data['173'] || '').padStart(34, ' ')
            + String(data['174'] || '').padStart(17, ' ')
            + String(data['175'] || '').padStart(70, ' ')
            + String(data['176'] || '').padStart(35, ' ')
            + String(data['177'] || '').padStart(30, ' ')
            + String(data['178'] || '').padStart(2, ' ')
            + String(data['179'] || " ").charAt(0)
            + " ".padStart(445, ' ')
            + "</T30303000>"
            + "</T3030" + year + trimester + "T0000>"
    }

    private getForm303Content2022(year: number, trimester: number, cifNif: string, name: string, tax: ITax): string {
        const data = tax.data
        // if (Object.values(data).length < 180) throw new HttpException(ResponseCodes.BAD_REQUEST, ResponseMessages.en.FORM_INVALID_DATA)
        return "<T3030" + year + trimester + "T0000><AUX>"
            + "2.05".padStart(70 + 4, ' ') // 70 blank + 4 version string
            + "B88476437".padStart(9 + 4, ' ') // 9 NIF + 4 blanks
            + "</AUX>".padStart(213 + 6, ' ') // 213 blank space + </AUX>
            + "<T30301000> A" //----- FIRST PAGE ------
            + cifNif
            + name.padEnd(80, ' ')
            + year
            + trimester
            + "T"
            + String(data['0'] || "2").charAt(0)
            + String(data['1'] || "2").charAt(0)
            + String(data['2'] || "3").charAt(0)
            + String(data['3'] || "2").charAt(0)
            + String(data['4'] || "2").charAt(0)
            + String(data['5'] || "2").charAt(0)
            + String(data['6'] || "2").charAt(0)
            + String(data['7'] || "2").charAt(0)
            + String(data['8'] || "2").charAt(0)
            + String(data['9'] || '').padStart(8, ' ')
            + String(data['10'] || " ").charAt(0)
            + String(data['11'] || "2").charAt(0)
            + String(data['12'] || "0").charAt(0)
            + String(data['13'] || "0").charAt(0)
            + numberToStr(data['14'], 17)
            + numberToStr(data['15'], 5)
            + numberToStr(data['16'], 17)
            + numberToStr(data['17'], 17)
            + numberToStr(data['18'], 5)
            + numberToStr(data['19'], 17)
            + numberToStr(data['20'], 17)
            + numberToStr(data['21'], 5)
            + numberToStr(data['22'], 17)
            + numberToStr(data['23'], 17)
            + numberToStr(data['24'], 17)
            + numberToStr(data['25'], 17)
            + numberToStr(data['26'], 17)
            + numberToStr(data['27'], 17)
            + numberToStr(data['28'], 17)
            + numberToStr(data['29'], 17)
            + numberToStr(data['30'], 5)
            + numberToStr(data['31'], 17)
            + numberToStr(data['32'], 17)
            + numberToStr(data['33'], 5)
            + numberToStr(data['34'], 17)
            + numberToStr(data['35'], 17)
            + numberToStr(data['36'], 5)
            + numberToStr(data['37'], 17)
            + numberToStr(data['38'], 17)
            + numberToStr(data['39'], 17)
            + numberToStr(data['40'], 17)
            + numberToStr(data['41'], 17)
            + numberToStr(data['42'], 17)
            + numberToStr(data['43'], 17)
            + numberToStr(data['44'], 17)
            + numberToStr(data['45'], 17)
            + numberToStr(data['46'], 17)
            + numberToStr(data['47'], 17)
            + numberToStr(data['48'], 17)
            + numberToStr(data['49'], 17)
            + numberToStr(data['50'], 17)
            + numberToStr(data['51'], 17)
            + numberToStr(data['52'], 17)
            + numberToStr(data['53'], 17)
            + numberToStr(data['54'], 17)
            + numberToStr(data['55'], 17)
            + numberToStr(data['56'], 17)
            + numberToStr(data['57'], 17)
            + numberToStr(data['58'], 17)
            + numberToStr(data['59'], 17)
            + "</T30301000>".padStart(600 + 13 + 12, ' ')    // 600 spaces + 13 spaces + 12 tag
            + "<T30302000>"//----- SECOND PAGE ------
            + String(data['60'] || " ").charAt(0)
            + String(data['61'] || '').padStart(2, '0')
            + numberToStr(data['62'], 17)
            + numberToStr(data['63'], 6, 100000)
            + numberToStr(data['64'], 17)
            + numberToStr(data['65'], 5)
            + numberToStr(data['66'], 17)
            + numberToStr(data['67'], 17)
            + numberToStr(data['68'], 17)
            + String(data['69'] || '').padStart(2, '0')
            + numberToStr(data['70'], 17)
            + numberToStr(data['71'], 6, 100000)
            + numberToStr(data['72'], 17)
            + numberToStr(data['73'], 5)
            + numberToStr(data['74'], 17)
            + numberToStr(data['75'], 17)
            + numberToStr(data['76'], 17)
            + String(data['77'] || '').padStart(4, ' ')
            + String(data['78'] || " ").charAt(0)
            + numberToStr(data['79'], 10)
            + numberToStr(data['80'], 17)
            + numberToStr(data['81'], 10)
            + numberToStr(data['82'], 17)
            + numberToStr(data['83'], 10)
            + numberToStr(data['84'], 17)
            + numberToStr(data['85'], 10)
            + numberToStr(data['86'], 17)
            + numberToStr(data['87'], 10)
            + numberToStr(data['88'], 17)
            + numberToStr(data['89'], 10)
            + numberToStr(data['90'], 17)
            + numberToStr(data['91'], 10)
            + numberToStr(data['92'], 17)
            + numberToStr(data['93'], 17)
            + numberToStr(data['94'], 17)
            + numberToStr(data['95'], 3)
            + numberToStr(data['96'], 5)
            + numberToStr(data['97'], 17)
            + numberToStr(data['98'], 17)
            + numberToStr(data['99'], 3)
            + numberToStr(data['100'], 17)
            + numberToStr(data['101'], 5)
            + numberToStr(data['102'], 17)
            + numberToStr(data['103'], 17)
            + numberToStr(data['104'], 17)
            + String(data['105'] || '').padStart(4, ' ')
            + String(data['106'] || " ").charAt(0)
            + numberToStr(data['107'], 10)
            + numberToStr(data['108'], 17)
            + numberToStr(data['109'], 10)
            + numberToStr(data['110'], 17)
            + numberToStr(data['111'], 10)
            + numberToStr(data['112'], 17)
            + numberToStr(data['113'], 10)
            + numberToStr(data['114'], 17)
            + numberToStr(data['115'], 10)
            + numberToStr(data['116'], 17)
            + numberToStr(data['117'], 10)
            + numberToStr(data['118'], 17)
            + numberToStr(data['119'], 10)
            + numberToStr(data['120'], 17)
            + numberToStr(data['121'], 17)
            + numberToStr(data['122'], 17)
            + numberToStr(data['123'], 3)
            + numberToStr(data['124'], 5)
            + numberToStr(data['125'], 17)
            + numberToStr(data['126'], 17)
            + numberToStr(data['127'], 3)
            + numberToStr(data['128'], 17)
            + numberToStr(data['129'], 5)
            + numberToStr(data['130'], 17)
            + numberToStr(data['131'], 17)
            + numberToStr(data['132'], 17)
            + numberToStr(data['133'], 17)
            + numberToStr(data['134'], 17)
            + numberToStr(data['135'], 17)
            + numberToStr(data['136'], 17)
            + numberToStr(data['137'], 17)
            + numberToStr(data['138'], 17)
            + numberToStr(data['139'], 17)
            + numberToStr(data['140'], 17)
            + numberToStr(data['141'], 17)
            + numberToStr(data['142'], 17)
            + numberToStr(data['143'], 17)
            + numberToStr(data['144'], 17)
            + "</T30302000>".padStart(590 + 12, ' ')    // 590 spaces + 12 tag


            + "<T30303000>"//----- THIRD PAGE ------
            + numberToStr(data['145'], 17)
            + numberToStr(data['146'], 17)
            + numberToStr(data['148'], 17)
            + numberToStr(data['150'], 17)
            + numberToStr(data['151'], 17)
            + numberToStr(data['152'], 17)
            + numberToStr(data['153'], 17)
            + numberToStr(data['154'], 17)
            + numberToStr(data['155'], 17)
            + numberToStr(data['156'], 17)
            + numberToStr(data['157'], 17)
            + numberToStr(data['158'], 17)
            + numberToStr(data['159'], 5)
            + numberToStr(data['160'], 17)
            + numberToStr(data['161'], 17)
            + numberToStr(data['162'], 17)
            + numberToStr(data['163'], 17)
            + numberToStr(data['164'], 17)
            + numberToStr(data['165'], 17)
            + numberToStr(data['166'], 17)
            + numberToStr(data['167'], 17)
            + numberToStr(data['168'], 17)
            + String(data['169'] || " ").charAt(0)
            + String(data['170'] || '').padStart(13, ' ')
            + String(data['171'] || " ").charAt(0)
            + String(data['172'] || '').padStart(11, ' ')
            + String(data['173'] || '').padStart(34, ' ')
            + String(data['174'] || '').padStart(17, ' ')
            + String(data['175'] || '').padStart(70, ' ')
            + String(data['176'] || '').padStart(35, ' ')
            + String(data['177'] || '').padStart(30, ' ')
            + String(data['178'] || '').padStart(2, ' ')
            + String(data['179'] || " ").charAt(0)
            + " ".padStart(600, ' ')
            + "</T30303000>"
            + "</T3030" + year + trimester + "T0000>"
    }
}

export default TaxService;
