# baseURL
@baseURL = http://localhost:3000/v3

# @baseURL = https://api.thegestor.app/v3


###
# User verify exists and send otp
POST {{ baseURL }}/verify-exists
Content-Type: application/json

{
    "email": "test@gmail.com",
    "phoneNumber": "9898989898",
    "countryCode":"+91"
}

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "countryCode": "+91",
    "phoneNumber": "9898989898",
    "otp": "123456",
    "userType": "freelancer",
    "password": "test1234",
    "cifNif": "test",
    "companyName": "Test Company",
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test1234"
}

