# baseURL
@baseURL = http://localhost:3001/v3

# @baseURL = https://api.thegestor.app/v3

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjJlYTY3MzZjYzhjMjg0MzMxNDMyZTY5In0sImlhdCI6MTY2MDA0NTI5MywiZXhwIjoxNjkxNTgxMjkzLCJhdWQiOiJkZXYiLCJpc3MiOiJ0aGVnZXN0b3JhcHAifQ.BaytKEl8GOL8xHSLAZOuww4fGUI5PCaIwSXj1UbZRFI


###
# Get Test form
# To save the form call "document.taxForm.submit()"
GET {{baseURL}}/form/view?type=form111&year=2022&trimester=1
Authorization: Bearer {{token}}


###
# Save Test form
POST {{baseURL}}/form/test
Content-Type: application/json

{
    "data":{
        "name": "Nilkanth",
        "address": "Test address",
        "city": "SURAT",
        "state": "GUJARAT",
        "country": "INDIA"
    }
}