import { Response } from "express";

export interface IApiResponse extends Response {
    success: (message: string, data?: any) => void
}

export enum ResponseCodes {
    SUCCESS = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    INTERNAL_SERVER_ERROR = 500
}

export const ResponseMessages = {
    en: {
        SOMETHING_WENT_WRONG: 'Something went wrong',
        WRONG_AUTH_TOKEN: 'Wrong authentication token',
        AUTH_TOKEN_MISSING: 'Authentication token missing',
        EMAIL_EXISTS: 'Email already exists',
        PHONE_EXISTS: 'Phone number already exists',
        OTP_SENT: 'OTP sent to your phone',
        OTP_EXPIRED: 'OTP has been expired',
        OTP_INCORRECT: 'OTP entered is incorrect',
        SIGNUP_SUCCESS: "User signup successfully",
        EMAIL_NOT_REGISTERED: "This email is not registered",
        PASSWORD_INCORRECT: "The password is incorrect",
        LOGIN_SUCCESS: "Login successfully",
        PLANS_FOUND: "Plans found",
        COUPON_NOT_FOUND: 'Coupon not found',
        COUPON_INVALID_PLAN: 'Coupon cannot be applied to selected plan',
        COUPON_CANNOT_REDEEM: 'Coupon cannot be redeemed by you',
        COUPON_USED: 'Coupon already used',
        COUPON_APPLIED_SUCCESS: 'Coupon applied successfully',
        COUPON_CREATED: 'Coupon created successfully',
        PLAN_NOT_FOUND: 'Plan not found',
        INVALID_COUPON_UNITS: 'Coupon cannot be applied to the given units',
        INVALID_BILLING_AMOUNT: 'Invalid billing amount',
        BILLING_CREATED: 'Billing created successfully',
        UNPAID_BILL_ERROR: 'Please pay your unpaid bills to purchase the subscription',
        NO_ACCESS_ERROR: 'You dont have access to the account',
        INVITE_NOT_ACCEPTED: 'You have not accepted the invite yet',
        EDIT_ACCESS_ERROR: 'You dont have edit access to the account',
        ADMIN_ACCESS_ERROR: 'You dont have admin access to the account',
        BILLINGS_FOUND: 'Billings found',
        INVALID_PAYMENT: 'Payment is not valid. Please contact support.',
        SUBSCRIPTION_CANCELED: 'Subscription canceled successfully',
        BILL_NOT_FOUND: 'Bill not found',
    },
    es: {
        SOMETHING_WENT_WRONG: 'Something went wrong',
        WRONG_AUTH_TOKEN: 'Wrong authentication token',
        AUTH_TOKEN_MISSING: 'Authentication token missing',
        EMAIL_EXISTS: 'Email already exists',
        PHONE_EXISTS: 'Phone number already exists',
        OTP_SENT: 'OTP sent to your phone',
        OTP_EXPIRED: 'OTP has been expired',
        OTP_INCORRECT: 'OTP entered is incorrect',
        SIGNUP_SUCCESS: "User signup successfully",
        EMAIL_NOT_REGISTERED: "This email is not registered",
        PASSWORD_INCORRECT: "The password is incorrect",
        LOGIN_SUCCESS: "Login successfully",
        PLANS_FOUND: "Plans found",
        COUPON_NOT_FOUND: 'Coupon not found',
        COUPON_INVALID_PLAN: 'Coupon cannot be applied to selected plan',
        COUPON_CANNOT_REDEEM: 'Coupon cannot be redeemed by you',
        COUPON_USED: 'Coupon already used',
        COUPON_APPLIED_SUCCESS: 'Coupon applied successfully',
        COUPON_CREATED: 'Coupon created successfully',
        PLAN_NOT_FOUND: 'Plan not found',
        INVALID_COUPON_UNITS: 'Coupon cannot be applied to the given units',
        INVALID_BILLING_AMOUNT: 'Invalid billing amount',
        BILLING_CREATED: 'Billing created successfully',
        UNPAID_BILL_ERROR: 'Please pay your unpaid bills to purchase the subscription',
        NO_ACCESS_ERROR: 'You dont have access to the account',
        INVITE_NOT_ACCEPTED: 'You have not accepted the invite yet',
        EDIT_ACCESS_ERROR: 'You dont have edit access to the account',
        ADMIN_ACCESS_ERROR: 'You dont have admin access to the account',
        BILLINGS_FOUND: 'Billings found',
        INVALID_PAYMENT: 'Payment is not valid. Please contact support.',
        SUBSCRIPTION_CANCELED: 'Subscription canceled successfully',
        BILL_NOT_FOUND: 'Bill not found',
    }
}